### ISSUE TITLE
Marcar disciplina como concluída.

### ISSUE THREAD

**Issue by raissonsouto** [raissonsouto/pijama-pro#3]
Marcar cadeiras como concluídas ajuda a diminuir o tamanho da lista, uma vez que se o aluno já pagou a disciplina, ele não precisa mais ficar olhando pra ela dentre as cadeiras disponíveis.

Importante detalhe dessa task é adicionar um checkbox na barra de pesquisa para dar a opção de mostrar ou não as disciplinas pagas.

**Comment by LazaroQueiroz** [comment]
Opa, assign me!

**Comment by raissonsouto** [comment]
Done
