### ISSUE TITLE
Verificação se cadeiras dão choque.

### ISSUE THREAD

**Issue by raissonsouto** [raissonsouto/pijama-pro#4]
Fazer o reconhecimento de cadeiras selecionadas que dão choque, existem alguns casos de uso para esse problema.

- Usuário seleciona uma cadeira, automaticamente cadeiras que dão choque ficam com fundo avermelhado sinalizando o conflito.
- Se mesmo assim o aluno colocar a disciplina na lista de selecionados, ele deve ter como observar melhor o choque entre as cadeiras na parte de grade semanal para entender como vai resolver o conflito e optar entre as cadeiras.
- Tornar possível esconder da lista cadeiras que dão choque.

**Comment by LazaroQueiroz** [comment]
Assign Me!
