### ISSUE TITLE
Barra de pesquisa dinâmica.

### ISSUE THREAD

**Issue by raissonsouto** [raissonsouto/pijama-pro#5]
Por agora, os períodos registrados, cursos, etc, são colocados de forma estatica no html. Seria interessante ter essa parte configurável, algo como um json que é consumido e passa quais os cursos tem pijama registrado, quais os períodos dos pijamas de cada curso, quantos períodos cada curso tem, etc.

**Comment by raissonsouto** [comment]
Versão inicial desse json:

https://raw.githubusercontent.com/raissonsouto/pijama2json/main/jsons/metadata.json

**Comment by LazaroQueiroz** [comment]
Opa, Assign me!

**Comment by raissonsouto** [comment]
Certo! Mas espera um pouco para implementar ... eu ainda vou mudar o formato do metadata.json no [pijama2json](https://github.com/raissonsouto/pijama2json).

Assim que eu resolver eu te pingo aqui.

**Comment by raissonsouto** [comment]
Pronto, mudei o formato do `metadata.json` :+1:
